name: LibraryAppBuild CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
    - name: Run tests
      run: mvn test
    - name: Generate Swagger documentation
      run: mvn compile
    - name: Validate Swagger documentation
      run: mvn validate
    - name: Publish Swagger documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./target/generated-docs/




    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
       image: saniazt/library-app-images
       tags: latest
       registry: docker.io
       dockerfile: Dockerfile
       username: saniazt
       password: Liop1mane
